### ISSUE TITLE
the dictionary may be better if it were a auto complete 

### ISSUE THREAD

**Issue by omgwtfidk89** [psoukie/zipchord#1]
i tried using a list of the 3000 most used words in English as a dictionary  but many words a like state and taste use the same letters  and i would need to individually  assign shortcuts.

**Comment by psoukie** [comment]
This aim of this project is to provide chorded entry in combination with touch typing. My focus is on having a tool that extends touch typing. The benefits of this are being able to type without looking and also not being distracted by considering auto-complete suggestions which appear as you type. (That's not to say auto-complete solutions are worse or not valid, just different philosophy.)

As you point out, many words map to the same keys, so the two possibilities are to either learn and use a complex system such as stenography machine that maps the same sounds/letters on two sides of the keyboard or define custom shortcuts.

I found that using mirroring tricks (inspired by stenography) is pretty easy to learn. So (on QWERTY keyboard) you could define:
STA for 'state' and TAL for 'state' (where the L is in mirror position of S).

Ultimately, it is about deciding which frequently used words a user wants to automate, define and learn.

If the ambition is to do a thousand or more words, the amount of learning (because how much you would be forced outside of natural key combinations) is such that you could consider learning stenography. Plover is a great open source stenotyping system  (https://github.com/openstenoproject/plover) but the amount of learning required is very high.
