### ISSUE TITLE
Chord behavior - Smart punctuation (using prefix tilde ~)

### ISSUE THREAD

**Issue by lmendez5** [psoukie/zipchord#10]
Hi there! hope you doing well! 
I am using all chords with prefix mode, with the tilde ~, in order to insert my own space (meanwhile new version is released), but Smart  Punctuation (chord option) is deleting last letter of the resultant word with a _prefix_ config, e. g. dictionary file `csl  = casual~` is launching the right result `casual ` -with ending space-, but if you add some punctuation (example, period <.>) script is retrieving: `casua.` The test is using the prefix configuration, but when just need the prefix itself is when this is happening. 

I was thinking about the suggested option is just about adding this tilde symbol if some checkbox is selected at the config panel... Anyway, I hope helping you with this littler bug 😄

**Comment by psoukie** [comment]
Thank you! This is now fixed in [this version](https://github.com/psoukie/zipchord/blob/updates/source/zipchord.ahk) in 'updates' branch.

I am now going to add the long-delayed change to let users choose not to have spaces added around chords. (And this should eliminate the need to use prefixes as workarounds.)
