### ISSUE TITLE
Special Key errors

### ISSUE THREAD

**Issue by lmendez5** [psoukie/zipchord#119]
**Describe the bug** - _A short description of the bug._
Because the two keys chords and speed of typing is a little tricky, I decided to give a chance to the Special Key Feature with `PrinScreen:| ` following [the instructions](https://github.com/psoukie/zipchord/issues/90#issuecomment-1371763291).  

_- What happens, and what do you expect to happen instead?_

The feature is working well, but with the `:` the PrintScreen is enable, always after casting a chord, the clipboard gets the image of the entire desktop. So, when the simple copy/paste action is required, this is not available. So, I tried to configure the `=` option in order to disable the functionality of the PrintScreen key, but I got the next message:

![image](https://user-images.githubusercontent.com/95358420/211913834-1148dab5-f9bc-4488-b7af-4755c3fb9512.png)

After playing around, setting the default "All keys" field, and save and close, and open again and inserting the special option, the program accepted the `{PrintScreen=|}` with no error. This is a little bug, but taking advantage of this post, I guess could help.

So, with the setting with `=` I expected the PrintScreen function was disabled and get my copy/paste functionality again, but the chording now is disable. I mean, the script cast no chord.

- Which settings do you have selected in the ZipChord settings?

![image](https://user-images.githubusercontent.com/95358420/211915478-43108886-09a3-4e7a-b9f3-e6033d004649.png)

When I tried to create a log file, I got the next error:

![image](https://user-images.githubusercontent.com/95358420/211915806-a0682e22-65a4-4af9-b14f-c34c1926a20b.png)

I did some chords, with this original key entries and, of course, holding the PrintScreen key: `ap cj en es ` and I got the next log file: [debug.txt](https://github.com/psoukie/zipchord/files/10395933/debug.txt)

So, I hope my explanation was enough good! hehehe

**Comment by psoukie** [comment]
I could not reproduce this problem, so the issue might be caused by something else. I documented what I did, step by step, so we can try and isolate the issue. 

I took two preliminary steps. (You should not need these, but you can try the first one if steps 1-11 alone don't give you the same result.)

* Delete ZipChord settings from Windows Registry (Open Registry Editor, navigate to Computer\HKEY_CURRENT_USER\SOFTWARE\ and select "ZipChord" and delete)
* Install Spanish keyboard in Windows 

1. Place a copy of zipchord.exe (I used 2.0.0-rc.1) into an empty folder. (To ensure we start with default locale settings and default dictionaries.)
2. Run ZipChord
3. Click **Customize** button under keyboard settings. (This disables key recognition until the settings are applied in step 7.)
4. Click **New** to create new locale settings, name it "Español"
5. Copy the keys under **All keys** (without adding space):
```
{PrintScreen=|}`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnñm,./
```
6. Click **Save Changes**, click **Close**
7. Click **OK** in the main ZipChord window (this restarts chording with the new settings) and close the pop-up window.
8. Switch to a Notepad or another editor and type normally "El Niño". Select the text and press and hold **Ctrl-C**. 
9. In the Add Shortcut window, type `|ñ` into the chord edit box and click **Save** next to it.
10. Then try to use the chord **Print Screen** and **ñ** (the key marked ;: on English keyboards). 

When I do this, I get "El Niño" and the clipboard remains untouched (so the PrintScreen function was bypassed).

Note on step 5: To get actual Spanish keyboard settings would take more adjustments but this is just to test things.

Thank you for testing all this, and please let me know what you get.

**Comment by lmendez5** [comment]
Well... it works with the normal procedure. I am really sorry, honestly I no have idea what was wrong... but sometimes it happens 🤷‍♂️... btw... great great job with hints... love them! thank you for your replies.

**Comment by psoukie** [comment]
There definitely are things that can go wrong when switching keyboard layouts or when applying "wrong" keys (keys that don't exist in the current layout) after changing the keyboard settings. I'm trying to make this part more resilient. 

I'm glad the feature works, but let me know when this happens again if you'll notice what triggered it.
