### ISSUE TITLE
Chords not always working

### ISSUE THREAD

**Issue by jsampson45** [psoukie/zipchord#142]
I reported this but the report seems to have disappeared. 
Sometimes shorthands stop working, e. g. "kj" for "change". "kj" appears instead of "change". 
If I press Return and start a new line the function is restored. 
I have had this problem while writing in Sublime Text and in Notepad++. 
I have not been able to find what causes it to stop working. 
This is Zipchord 2, and I have not changed the settings from default.

**Comment by psoukie** [comment]
Apologies, it might have been closed when I assumed this was no longer as issue.

It would be great if we could find a series of steps that can reliably reproduce this issue. 

One thing to try -- I released a "debug" version of ZipChord that has some extra features. If you use that version, you can open a "Key Visualizer" from the ZipChord tray menu. if you leave it open as you type in these applications, you could notice if the key presses actually at some point stop being recognized/visualized by ZipChord. 

The "Debug" version does not store or send any data so it's completely private to test what's happening. (Unless you manually decide to save the input/output to a local file using the console).

**Comment by psoukie** [comment]
The other thing you can try is the following: 

1. Download the zipchord-dev version under the [latest release](https://github.com/psoukie/zipchord/releases/tag/2.1.0-beta)
2. On the About tab of this version, check the "Log this session (debugging)" option. 
3. Type some short text in the application where you experience the problem.
4. Re-open the ZipChord window. This will stop the debugging and will open a text file with the debug information.

If you could attach the debug file here, I'm going to see what might be going causing the issue.  But it could be that in those applications, some keypresses -- for some reason -- are not being sent to ZipChord. That's why I suggested trying the Key Visualizer first.
