### ISSUE TITLE
Shortcut expansion leaves the first letter in place when done with an apostrophe

### ISSUE THREAD

**Issue by Adrakaris** [psoukie/zipchord#164]
Upon writing a shorthand code, and then pressing an apostrophe, it seems to leave the first letter behind.

So if I type "first" using first, and then completing with an apostrophe, it ends up looking like ffirst'

Edit: actually, it seems to work well enough in github. I'm using obsidianmd, so perhaps it's an obsidian thing

**Comment by psoukie** [comment]
Thank you for reporting this! Indeed, I think it's because obsidian is doing some replacement on the apostrophe in a way that disrupts the replacement done by Obsidian. You could experiment with using an Output Delay (on the Output tab) to see if that resolves it. 
For example, Word replaces apostrophe's with curly versions, but in a way that does not disrupt ZipChord. 
I'm going to mark this as an external issue, but will keep an eye on a potential workaround or fix.
