### ISSUE TITLE
Abort facility not found

### ISSUE THREAD

**Issue by jsampson45** [psoukie/zipchord#18]
I have downloaded what I think is the latest version but I am not a Github expert so it may not be. What I have downloaded does not allow one to bail out if the dictionary being opened has many errors. Also, the errors may be obscure e.g. finding chords in the file which cannot be found when viewing the dictionary in a text editor (perhaps the chords have their characters in a different order). It is mentioned that if used with an NKRO keyboard Zipchord might be used to emulate steno. For this it would be necessary to load a dictionary, and to be able to find and fix errors in it.

**Comment by psoukie** [comment]
Thank you for getting back to me on the finding. The [latest release](https://github.com/psoukie/zipchord/releases/tag/v.1.7.1) lets me abort loading a dictionary after the first error. Can you try and let me know? (The first dialog should explain the error found, and then there should be a second dialg asking whether you want to continue loading the dictionary.) If it does not work for you, could you send me an example dictionary where this happens?

You are right that the chord keys in the error message are ordered alphabetically, so to search for the entry in the text file, use the word indicated in the message. For example:

```
The chord 'dir' is already in use for 'direction'.
Please use a different chord for 'ride'.
```

So in this example, I would search for the word "ride" or "direction" in the text file because both of them are assigned the same chord.

Steno keyboards use strategies that have the same sounds assigned to key combinations on both left and right hand of the keyboard to help differentiate things like "pan" and "nap". Even though the idea behind ZipChord was to use it for only frequently used words to supplement regular typing, it technically can emulate steno. For troubleshooting a very large dictionary though, a spreadsheet might be a better tool to do it -- break the chords into individual characters and sort them alphabetically, and check for duplicates.
