### ISSUE TITLE
Feature Request: quickly delete the up to the last full word

### ISSUE THREAD

**Issue by drphil3d** [psoukie/zipchord#2]
Some way to delete all the characters that didn't form a complete chord but are just random letters instead of having to backspace a lot of times?

**Comment by URFIR3D** [comment]
Agreed, this would be a very useful feature. It would also bring the app more in line with CharaChorder. There is def plenty of times where mistakes are made while typing.

**Comment by psoukie** [comment]
This is a great suggestion. I am sorry for the delay in responding. I have been sick for the past few weeks. This should be hopefully a straightforward fix, and I hope to release it this weekend at the latest.

**Comment by psoukie** [comment]
This should now be working in the latest release. Note that it is not enabled by default because I suspect a lot of people tend to type with leaving multiple keys pressed longer than they realize. When using the new feature, make the chord sensitivity delay longer if it will be causing problems. Please let me know if this is working well for you now.

**Comment by drphil3d** [comment]
You're awesome! Thanks!
