### ISSUE TITLE
"Each key can be entered only once in the same chord." when adding the "shorthands-english.txt" dictionary. 

### ISSUE THREAD

**Issue by maxultimus** [psoukie/zipchord#56]
"Each key can be entered only once in the same chord." when adding the "shorthands-english.txt" dictionary. What am I doing wrong?
![image](https://user-images.githubusercontent.com/72915303/209774794-45be2f5d-78a5-4691-b426-35a00dc7f553.png)

**Comment by maxultimus** [comment]
Perhaps the shorthands-english.txt dictionary has duplicte chords. I could not find a nice way to edit in mass.

**Comment by psoukie** [comment]
I notice there was a bug when using UI to open a different shorthands dictionary file. Can you please check if there is the same error when using the [alpha 2 release](https://github.com/psoukie/zipchord/releases/tag/2.0.0-alpha.2)?

**Comment by maxultimus** [comment]
![image](https://user-images.githubusercontent.com/72915303/209786811-80ec2ee0-a309-4378-b0b5-47ead57990cd.png)
The error is gone, thanks. 

Perhaps unreleated (let me know if I should open a new bug):
- First dictionary will output words directly after the chord, whilst the second dictionary requires entering a space after the word to output it.
- if the same chord is defined in both it seems to chose the output auto random. I will only use one dictionary.

**Comment by psoukie** [comment]
Thank you! The shorthands are under development (not part of stable release), so this is great feedback.
* I just included your first bullet under #52 to create a detection setting that does not wait for space or punctuation. The option will be useful, because when requiring a space or punctuation, more shorthands can be defined (even one-letter ones) without triggering unintended words when the same sequence appears at the start of a word in regular typing.
* For the second one, please go ahead and create a separate bug. I could not replicate it so more details would be helpful about when it happens. Optionally, you could try to check the "Log this session" option on About tab, press OK, and type the sequence that triggers this, and then re-open the ZipChord menu. This will open a newly created log file, and you can then copy paste the actual output of your typing to the top of the log file, and attach it to the issue.

I'm going to close this issue once the new one is open. Thank you again. Great bug reports!

**Comment by maxultimus** [comment]
Thank you for the quick turnarou you. I could not reproduce the second one and now assume it was user error.
Happy new year.

**Comment by psoukie** [comment]
Thank you again for the original report and letting me know about the update.

I should have a new 2.0 preview out later today with on-screen tips for shortcuts. (Before heading back to my regular job.)

Happy New Year!
