### ISSUE TITLE
space at the end - suggestion

### ISSUE THREAD

**Issue by lmendez5** [psoukie/zipchord#9]
**Wonderful wonderful wonderful work guys!** 
As a suggestion, when one is typing and chording is a custom to press the spacebar, maybe not for all people, but in the config window would be great to have a checkbox to "add or not" a space at the end of the desired string.
 
![image](https://user-images.githubusercontent.com/95358420/202754051-3c21e1b7-7b5c-40cb-a24b-302b133a2a78.png)

**Comment by lmendez5** [comment]
updating... I realized the smart punctuation pretends doing it, but, two things... one, is stick with capitalizing and two, actually is not working. I try to set it to off but same behavior... but still I have to say it: awesome script!

**Comment by psoukie** [comment]
Thank you, Luis!

I agree that the “Smart punctuation” feature is currently doing too many things (dynamic spacing, capitalization) which is a bit confusing and doesn’t allow all combinations.

If I understand correctly what you are looking for: a setting where ZipChord would not add a space after a chord, correct? (So let’s say if two words entered using chords follow each other, you’d press the first chord, then space bar, and then press the next chord.)

I’m thinking of separating the options, which should make it easier to configure and understand the settings. How would this work?

**Smart spaces**
- [ ] Before chords  _Add spaces in front of chords, unless you typed a space already._
- [ ] After chords  _Add spaces after the chords which will be removed if you type space or punctuation next._
- [ ] After punctuation  _Add spaces after punctuation which will be removed if you type space next._

**Smart capitalization**:  Off / For chords / For all input _Changes the first letter to uppercase when it follows punctuation._

**Comment by lmendez5** [comment]
Hi Pavel,  you got it! that's right. Because is a mix typing,  well,  sometimes I got double space by inertia. I know,  maybe is about get used to,  but could be cool the have in configuration. I think Smart-Punctuation (besides is handling a lot and has improving opportunities) is doing pretty well... On the other hand,  I had to modify a little the script,  because I am building a Spanish dictionary and maybe you want to know the script works pretty good with Spanish symbols, not a single problem! btw with a couple of days practicing 139 wpm hahaha from an average of 80 😄 of course,  all depends the random words at monkeytype and a good warmup hahaha well,  thank you for replay and any update,  suggestion or testing,  count on me! gracias!

**Comment by psoukie** [comment]
As the first step, I improved the smart punctuation to prevent two spaces in situations where ZipChord inserts a smart space and then the user presses the space bar. This should work after a chord as well as after punctuation.

I am still going to implement the bigger change as outlined. But can you please check if it is working for you? The updated code is here: https://github.com/psoukie/zipchord/blob/main/source/zipchord.ahk

I'd be also interested to see the modifications you made -- maybe they are things that could be useful for everyone, or for other languages too.

**Comment by lmendez5** [comment]
Hi there! it is working great! 👍 the first space is deleted and if I need (for any reason) insert others, the script allow it. 
About testing Spanish symbols, not big deal! Just adding to global keys  `ñ, ¿, ´, ` (last one is an accent mark) and no problem at all using the Spanish layout.
I was having some troubles with random failing chords, but (in case happening to somebody else) was because I had activated my automatic shift at my Planck EZ. So, is just about deactivate it and everything runs as expected. Of course, now I am finding the best layout for Shifting again hahaha, but this master piece of script worthy it!
Thank you! Waiting for any update!

**Comment by psoukie** [comment]
That's very interesting. I have just updated the script to allow definition of custom keys within the dictionary file.
To use it, put a "custom_keys" and then a Tab (as usual) and a list of all the characters that can be typed (without Shift or any modifier keys) somewhere in the dictionary file. I might be able to eventually modify 

For example, in English QWERTY (already included by default), it could be:
`custom_keys	qwertyuiop[]asdfghjkl;'zxcvbnm,./`

ZipChord does not play nicely with Shift because it's quite complicated. Regardless, for Spanish (or other keyboards), people should only need to type in all the unmodified keys for `custom_keys` that they want to be using for chords. Unfortunately, there are still some other language-specific keyboard assumptions I'm using about where punctuation is on the keyboard -- I will try to fix that in that future.

I still haven't modified the settings, but this gave me an opportunity to make more improvements. Let me know if it works for you.

**Comment by lmendez5** [comment]
thank you! It works pretty well! here is a little test: 

![image](https://user-images.githubusercontent.com/95358420/203443731-469af77e-4912-41ba-a256-4047cfa85889.png)

There is something could be an improvement, is about fast typing triggering a chord between the word is being typed. Maybe if the chord could be able to detect if there is an space before it, else is not a desired chord. For instance, I am typing the word `centena` but I have the chord `ent=entonces` so the script is triggering `c entonces ena`. Tell me if make sense to you, or maybe it happens to you as well. 

This script is a great partner alongside keyboard and mouse customization!
very nice work! 🤝

**Comment by lmendez5** [comment]
Hi Pavel, how you doing?

well, this time I tried to fix the typing fast thing... till now (generally) this change is working but maybe you want to take a look. There are some tags "lmendez" where I comment briefly why I wrote the code. Is not the most elegant solution hehehe, compare with your code maybe it look like a bad joke! hahaha but now I am typing whole words with "chords" inside and no problem. Indeed, I have tested it with 25ms delay. However, it has a little issue when select all delete and try the first chord. Weird, but using a single space will work. 

https://drive.google.com/file/d/1t_k9AgAb97lTrfxq5T5xN3prxbqHAq5J/view?usp=share_link

Also, I am working into another idea. Root-words! the main idea is about words that needs some root, for instance casually, totally, fixedly... for instance, if you have a chord for "final" and you just want to add an "s" at the end in order to write the plural "finals", but also will work with "final"+ly to write "finally". In  Spanish we have, for instance the word "respetar" (respect) and you can combine to form multiple words "respetar, respetarlo, respetarla, respetarse" and I have a chord for the first one and simply write the ending. This is still in testing and was just about playing with the "lastentry" values and other stuff you of course know!

Well, sorry for "the sacrilege" inserting thins in your beautiful code, but if you have a best solution (I bet yes) maybe I can add some value in order to launch ideas. Thank you for sharing your script! Take care!

**Comment by psoukie** [comment]
Thank you, Luis! This week is super busy for me with work (even though it's holidays in the US, I'll need to work a lot for my day job.)  I love the idea with the space as an (optional) prerequisite for the chord. For the roots of words -- once I have the version where spaces following chords is optional, that is one way to do it. Another way you could do is to define the words as prepositions (with ~ at the end) -- that way, there would not be a space after the word (even without the setting). Another option is to define suffixes. In my dictionary, I use both (prefixes and suffixes). I'll be able to review your code hopefully during this weekend. One last thing: if things are getting deleted, you can try to uncheck the box that deletes unknown chords -- that should help with it.

Apologies if I missed something, it's been super busy, but I'll re-read your post. Again, for the space and then a chord, I think that's a great idea, and could even be extended to two chords in a row, or a prefix chord and then a chord etc. So that could help a lot in general!

**Comment by lmendez5** [comment]
Hey Pavel! don't worry about time... job is always first! I had some time because I got COVID and I was in quarantine 😷 but today I am back to the office, so lot of work piled too! haha I will try the pre/suffix feature, I didn't know that! cooool! Thank you for the tip unchecking the mistyped chords, it helps as you said. When you have ready any update let me know to try it, I am glad to test and feedback you! 
Take care and enjoy Thanksgiving! Blessing for you and your loved ones!

**Comment by psoukie** [comment]
I am glad you recovered well and were able to go back to the office! I haven't had an opportunity to work on ZipChord for a few weeks, but now I made several changes to fix bugs and to make the long-awaited change to UI, and separate the smart spaces from capitalization.

As before, when smart spaces are enabled, they should play nice in combination with manual spaces (so if there is already a space, there shouldn't be another added, and if a space is needed but is not manually typed, it is added).  But the difference is that now there is a more fine-tuned control of the settings, and the spaces and capitalization are separated. (The spacing around punctuation is currently very basic, and English-focused. It's on my roadmap, together with improvements for the chord detection.)

Thank you again for suggesting this change, Luis. Let me know if you see any bugs, or have any suggestions for how to modify the functionality.
